### ISSUE TITLE
Feature request: pass config flags to Rofi

### ISSUE THREAD

**Issue by eater** [hugokernel/todofi.sh#12]
This would allow customizing the Rofi font, theme, and layout.

**Comment by kheraud** [comment]
You can already do it with `~/.config/todofish.conf`. You just have to override `ROFI_BIN="$(command -v rofi)"` with for example `ROFI_BIN="$(command -v rofi) -theme /usr/share/rofi/themes/fancy.rasi"`

**Comment by hugokernel** [comment]
Thx @kheraud
