### ISSUE TITLE
todo.sh is not run

### ISSUE THREAD

**Issue by jdsnape** [hugokernel/todofi.sh#15]
Although there's a check for todo.sh instead of todo-txt, when the script actually runs the command it's hard-coded to todo-txt:

https://github.com/hugokernel/todofi.sh/blob/35b4e27b552ac7c3bd5e8901c545fafa943b2461/todofi.sh#L59

I fixed it by changing that line to: 
```
    $TODO_BIN -p -d "$TODOTXT_CFG_FILE" "$@"
```

**Comment by hugokernel** [comment]
:+1: Thx
