### ISSUE TITLE
Add docs for how to theme todofi.sh

### ISSUE THREAD

**Issue by tommyalatalo** [hugokernel/todofi.sh#19]
The screenshot in the readme shows todofi.sh using the gruvbox theme.
I would like to have exactly the same theme, but I'm pretty new to rofi, and I don't see how I can theme the dialog using the todofi.sh script?

It would be good to have an example of how to manage theming for todofi.sh.

**Comment by kheraud** [comment]
You can edit `.config/rofi/config` :
```
rofi.font: "RobotoMono Nerd Font Mono" 14
rofi.show-icons: true
rofi.terminal: urxvt
rofi.m: -4
rofi.theme: /usr/share/rofi/themes/gruvbox-light-soft.rasi
```

You can find all this config options with `man rofi` and `man rofi-theme`

**Comment by tommyalatalo** [comment]
Okay yeah, that explains it. I'm using cli flags to set themes and other settings in a launcher script which is called by i3 in my case.
From what I can tell todofi.sh wraps rofi in such a way that using cli flags is not possible?

I'll look at setting this up using the config file instead, thanks

**Comment by hugokernel** [comment]
@kheraud explains it very well in this comment https://github.com/hugokernel/todofi.sh/issues/12#issuecomment-813908388

**Comment by tommyalatalo** [comment]
> @kheraud explains it very well in this comment [#12 (comment)](https://github.com/hugokernel/todofi.sh/issues/12#issuecomment-813908388)

The content of that comment would be very good to place in the readme.

**Comment by hugokernel** [comment]
Now in Readme https://github.com/hugokernel/todofi.sh#customization
