### ISSUE TITLE
Make check for todotxt script reliable

### ISSUE THREAD

**Issue by jose1711** [hugokernel/todofi.sh#3]
https://github.com/hugokernel/todofi.sh/blob/3b994edd2dadd039e2901752b886e6c456456a79/todofi.sh#L36

`whereis` also matches directories and this makes the test unreliable:
```
~ whereis -b todotxt | awk '{print $2}'
/usr/share/todotxt
~ todotxt
zsh: command not found: todotxt
~ ls -ld /usr/share/todotxt
drwxr-xr-x 2 root root 4096 jún  7 22:09 /usr/share/todotxt
```

**Comment by hugokernel** [comment]
Hi,
Thx for the ticket.
Some literature about that https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then/85250#85250
I think i will replace `whereis` with` type -P`, i have to do some tests.
