### ISSUE TITLE
Integration as mode in rofi?

### ISSUE THREAD

**Issue by BatmansGehilfe** [hugokernel/todofi.sh#7]
Is there a way to add todofi.sh as a mode to rofi?
I tried it like this:
`rofi.modi:			drun,todofi:todofi.sh -c /home/hd/.config/todo/config,calc:qalc +u8,window`

There is no error message, but the resulting mode just shows the output of `todofi.sh --help`.

No matter if I use -c / -d or no argument at all - nothing changes.

Any help is greatly appreciated!

**Comment by hugokernel** [comment]
Hi,
Use the output of todo-txt.sh directly, not the todofi output:

`rofi.modi: drun,todo:todo-txt -p -d /home/hd/.config/todo/config,calc:qalc +u8,window`

-p arg is for disabled the colored output.
